{% set name = "cf-units" %}
{% set version = "3.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88a9f140e4157fe4c2d322b5e079046c4c0a7d76cb4950c700a8363bc235074f
  patches:
    # Antlr version
    - backport_368.patch
    # Numpy 2.0
    - backport_427.patch

build:
  number: 5
  skip: True  # [py<=38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    - setuptools-scm
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime >=1.5.2
    - antlr-python-runtime 4.11.1.*
    - jinja2

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units

about:
  home: https://cf-units.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Units of measure as required by the Climate and Forecast (CF) Metadata Conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
    - pp-mo
